#Redisson配置
#singleServerConfig:
#  address: "redis://192.168.100.126:6379"
#  password: "xy_123456"
#  clientName: null                            #客户端名称
#  database: 0                                 #选择使用哪个数据库0~15
#  idleConnectionTimeout: 10000                #连接空闲超时, 单位:毫秒
#  pingTimeout: 1000                           #ping节点超时,单位:毫秒,默认1000
#  connectTimeout: 10000                       #连接等待超时,单位:毫秒,默认10000
#  timeout: 3000                               #命令等待超时,单位:毫秒,默认3000, 等待节点回复命令的时间, 该时间从命令发送成功时开始计时
#  retryAttempts: 3                            #命令失败重试次数, 默认值:3
#  retryInterval: 1500                         #命令重试发送时间间隔, 单位:毫秒, 默认值:1500
#  subscriptionsPerConnection: 5               #单个连接最大订阅数量, 默认值:5
#  subscriptionConnectionMinimumIdleSize: 1    #长期保持一定数量的发布订阅连接是必须的
#  subscriptionConnectionPoolSize: 50          #发布和订阅连接池大小, 默认值:50
#  connectionMinimumIdleSize: 32               #最小空闲连接数,默认值:10,最小保持连接数（长连接）
#  connectionPoolSize: 64                      #连接池最大容量. 默认值:64; 连接池的连接数量自动弹性伸缩
#  dnsMonitoringInterval: 5000                 #DNS监测时间间隔, 单位:毫秒, 默认值:5000
#threads: 1
#nettyThreads: 1
#codec:
#  class: "org.redisson.codec.JsonJacksonCodec"
#transportMode: "NIO"



#Redisson配置
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"